
[project]
name = "psychopy"
dynamic = ["version"]
requires-python = ">=3.9, <3.12"
description = "PsychoPy provides easy, precise, flexible experiments in behavioural sciences"
readme ={file = "README.md", content-type = "text/markdown"}
authors = [
    {name = "Open Science Tools Ltd", email = "support@opensciencetools.org"},
]
maintainers = [
    {name = "Open Science Tools Ltd", email = "support@opensciencetools.org"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    ]
    
dependencies = [
    "arabic-reshaper==3.0.0",
    "astunparse==1.6.3",
    "beautifulsoup4==4.14.3",
    "blosc2==3.12.2",
    "certifi==2026.1.4",
    "cffi==2.0.0",
    "charset-normalizer==3.4.4",
    "colorama==0.4.6; platform_system == 'Windows'",
    "contourpy==1.3.2",
    "cryptography==46.0.3",
    "cycler==0.12.1",
    "decorator==5.2.1",
    "elementpath==5.1.0",
    "et-xmlfile==2.0.0",
    "ffpyplayer==4.5.3",
    "fonttools==4.61.1",
    "freetype-py==2.5.1",
    "future==1.0.0",
    "gevent==25.5.1",
    "greenlet==3.3.0",
    "idna==3.11",
    "imageio==2.37.2",
    "imageio-ffmpeg==0.6.0",
    "jedi==0.19.2",
    "json-tricks==3.17.3",
    "kiwisolver==1.4.9",
    "markdown-it-py==4.0.0",
    "matplotlib==3.10.8",
    "mdurl==0.1.2",
    "meshpy==2025.1.1",
    "moviepy==2.2.1",
    "msgpack==1.1.2",
    "msgpack-numpy==0.4.8",
    "ndindex==1.10.1",
    "numexpr==2.14.1",
    "numpy==2.2.6",
    "opencv-python==4.12.0.88",
    "openpyxl==3.1.5",
    "packaging==25.0",
    "pandas==2.3.3",
    "parso==0.8.5",
    "pillow==11.3.0",
    "platformdirs==4.5.1",
    "proglog==0.1.12",
    "psutil==7.2.1",
    "psychtoolbox==3.0.19.14",
    "py-cpuinfo==9.0.0",
    "pyarrow==22.0.0",
    "pycparser==2.23",
    "pyglet==1.5.27",
    "pyparallel==0.2.2; platform_system == 'Windows'",
    "pyparsing==3.3.1",
    "pypiwin32==223; platform_system == 'Windows'",
    "pyqt6==6.10.2",
    "pyqt6-qt6==6.10.1",
    "pyqt6-sip==13.10.3",
    "pyserial==3.5",
    "python-bidi==0.6.7",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.2.1",
    "pytz==2025.2",
    "pywin32==311; platform_system == 'Windows'",
    "pywinhook==1.6.2; platform_system == 'Windows'",
    "pyyaml==6.0.3",
    "pyzmq==27.1.0",
    "questplus==2023.1",
    "requests==2.32.5",
    "scipy==1.14.1",
    "setuptools==70.3.0",
    "six==1.17.0",
    "soundfile==0.13.1",
    "soupsieve==2.8.1",
    "tables==3.10.1",
    "tqdm==4.67.1",
    "typing-extensions==4.15.0",
    "tzdata==2025.3",
    "ujson==5.11.0",
    "urllib3==2.6.3",
    "websockets==15.0.1",
    "wheel==0.45.1",
    "xarray==2025.6.1",
    "xmlschema==4.3.0",
    "zope-event==5.0",
    "zope-interface==7.2",
    "ifaddr==0.2.0; platform_system == 'Darwin'",
    "pyobjc==12.1; platform_system == 'Darwin'",
    "pyobjc-core==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-accessibility==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-accounts==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-addressbook==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-adservices==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-adsupport==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-applescriptkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-applescriptobjc==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-applicationservices==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-apptrackingtransparency==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-audiovideobridging==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-authenticationservices==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-automaticassessmentconfiguration==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-automator==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-avfoundation==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-avkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-businesschat==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-callkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-carbon==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-cfnetwork==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-classkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-cloudkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-cocoa==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-colorsync==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-contacts==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-contactsui==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-coreaudio==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-coreaudiokit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-corebluetooth==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-coredata==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-corehaptics==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-corelocation==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-coremedia==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-coremediaio==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-coremidi==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-coreml==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-coremotion==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-coreservices==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-corespotlight==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-coretext==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-corewlan==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-cryptotokenkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-datadetection==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-devicecheck==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-discrecording==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-discrecordingui==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-diskarbitration==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-dvdplayback==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-eventkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-exceptionhandling==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-executionpolicy==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-externalaccessory==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-fileprovider==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-fileproviderui==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-findersync==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-fsevents==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-gamecenter==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-gamecontroller==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-gamekit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-gameplaykit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-imagecapturecore==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-installerplugins==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-intents==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-intentsui==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-iobluetooth==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-iobluetoothui==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-iosurface==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-ituneslibrary==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-kernelmanagement==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-latentsemanticmapping==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-launchservices==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-libdispatch==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-libxpc==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-linkpresentation==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-localauthentication==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-localauthenticationembeddedui==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-mailkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-mapkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-mediaaccessibility==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-medialibrary==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-mediaplayer==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-mediatoolbox==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-metal==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-metalkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-metalperformanceshaders==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-metalperformanceshadersgraph==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-metrickit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-mlcompute==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-modelio==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-multipeerconnectivity==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-naturallanguage==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-netfs==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-network==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-networkextension==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-notificationcenter==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-opendirectory==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-osakit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-oslog==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-passkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-pencilkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-phase==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-photos==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-photosui==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-preferencepanes==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-pushkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-quartz==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-quicklookthumbnailing==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-replaykit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-safariservices==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-scenekit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-screencapturekit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-screensaver==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-screentime==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-scriptingbridge==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-searchkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-security==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-securityfoundation==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-securityinterface==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-servicemanagement==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-shazamkit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-social==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-soundanalysis==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-speech==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-spritekit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-storekit==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-syncservices==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-systemconfiguration==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-systemextensions==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-uniformtypeidentifiers==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-usernotifications==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-usernotificationsui==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-videosubscriberaccount==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-videotoolbox==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-virtualization==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-vision==12.1; platform_system == 'Darwin'",
    "pyobjc-framework-webkit==12.1; platform_system == 'Darwin'",
    "zeroconf==0.148.0; platform_system == 'Darwin'"
]

[project.optional-dependencies]  # This is optional dependencies
tests = [
    "pytest>=6.2.5",
    "pytest-codecov",
    "pytest-cov",
    "pytest-asyncio",
    "flake8",
    "xmlschema",
]
docs = [
    "sphinx",
    "jinja2",
    "sphinx-design",
    "sphinx-copybutton",
    "myst-parser",
    "sphinxcontrib.svg2pdfconverter",  # requires inkscape
    "psychopy-sphinx-theme",
]
building = [
    "bdist-mpkg>=0.5.0; platform_system == \"Darwin\"",
    "py2app; platform_system == \"Darwin\"",
    "dmgbuild; platform_system == \"Darwin\"",
    "polib",
]
suggested = [
    "sounddevice",
    "pylsl>=1.16.1", # lab streaming layer for general connectivity
    "xlwt",  # writing excel files with pandas
    "h5py<3.15.0",  # to read hdf5 files for analysis
    "tobii_research",
    "badapted>=0.0.3",
    "egi-pynetstation>=1.0.0",
    "pyxid2>=1.0.5",
    "Phidget22",
]
legacy = [
    "pyo>=1.0.3",
    "pyglfw",
    "pygame",
]

[project.urls]
Homepage = "https://www.psychopy.org/"
Download = "https://github.com/psychopy/psychopy/releases/"

[project.gui-scripts]
psychopy = "psychopy.app.psychopyApp:main"

[build-system]
requires = [
    "pdm-backend",
    "distro; platform_system == \"Linux\"",
    "tomlkit",
    "packaging",
    "six",  # for configobj
    "polib", # for compiling translation files (*.po)
    ]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = []
excludes = ["building/"]
#source-includes = ["tests/"]

[tool.pdm.version]
source = "call"
getter = "psychopy.__init__:getVersion"

[tool.distutils.bdist_wheel]
universal = 1

[tool.psychopy]
src = ["psychopy"]
