
[project]
name = "psychopy-lib"
dynamic = ["version"]
requires-python = ">=3.8, <3.11"
description = "PsychoPy provides easy, precise, flexible experiments in behavioural sciences"
readme ={file = "README.md", content-type = "text/markdown"}
authors = [
    {name = "Open Science Tools Ltd", email = "support@opensciencetools.org"},
]
maintainers = [
    {name = "Open Science Tools Ltd", email = "support@opensciencetools.org"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    ]
    
dependencies = [
    "arabic-reshaper==3.0.0",
    "astunparse==1.6.3",
    "blosc2==3.3.2",
    "certifi==2025.4.26",
    "cffi==1.17.1",
    "charset-normalizer==3.4.2",
    "colorama==0.4.6; platform_system == \"Windows\"",
    "contourpy==1.3.2",
    "cryptography==44.0.3",
    "cycler==0.12.1",
    "decorator==5.2.1",
    "elementpath==5.0.1",
    "et-xmlfile==2.0.0",
    "ffpyplayer==4.5.2",
    "fonttools==4.58.0",
    "freetype-py==2.5.1",
    "future==1.0.0",
    "gevent==25.5.1",
    "greenlet==3.2.2",
    "idna==3.10",
    "imageio==2.37.0",
    "imageio-ffmpeg==0.6.0",
    "jedi==0.19.2",
    "json-tricks==3.17.3",
    "kiwisolver==1.4.8",
    "markdown-it-py==3.0.0",
    "matplotlib==3.10.3",
    "mdurl==0.1.2",
    "meshpy==2025.1.1",
    "moviepy==2.1.2",
    "msgpack==1.1.0",
    "msgpack-numpy==0.4.8",
    "ndindex==1.9.2",
    "numexpr==2.10.2",
    "numpy==2.2.6",
    "opencv-python==4.11.0.86",
    "openpyxl==3.1.5",
    "packaging==25.0",
    "pandas==2.3.0",
    "parso==0.8.4",
    "pillow==10.4.0",
    "platformdirs==4.3.8",
    "proglog==0.1.12",
    "psutil==7.0.0",
    "psychtoolbox==3.0.19.14",
    "py-cpuinfo==9.0.0",
    "pyarrow==20.0.0",
    "pycparser==2.22",
    "pyglet==1.5.27",
    "pyparallel==0.2.2; platform_system == \"Windows\"",
    "pyparsing==3.2.3",
    "pypiwin32==223; platform_system == \"Windows\"",
    "pyqt6==6.9.0",
    "pyqt6-qt6==6.9.0",
    "pyqt6-sip==13.10.0",
    "pyserial==3.5",
    "python-bidi==0.6.6",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "pywin32==310; platform_system == \"Windows\"",
    "pywinhook==1.6.2; platform_system == \"Windows\"",
    "pyyaml==6.0.2",
    "pyzmq==26.4.0",
    "questplus==2023.1",
    "requests==2.32.3",
    "scipy==1.15.3",
    "setuptools==70.3.0",
    "six==1.17.0",
    "soundfile==0.13.1",
    "tables==3.10.1",
    "tqdm==4.67.1",
    "typing-extensions==4.13.2",
    "tzdata==2025.2",
    "ujson==5.10.0",
    "urllib3==2.4.0",
    "websockets==15.0.1",
    "wheel==0.45.1",
    "xarray==2025.4.0",
    "xmlschema==4.0.1",
    "zope-event==5.0",
    "zope-interface==7.2",
    "ifaddr==0.2.0; platform_system == \"Darwin\"",
    "pyobjc==7.3; platform_system == \"Darwin\"",
    "pyobjc-core==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-accessibility==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-accounts==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-addressbook==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-adservices==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-adsupport==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-applescriptkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-applescriptobjc==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-applicationservices==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-apptrackingtransparency==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-authenticationservices==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-automaticassessmentconfiguration==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-automator==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-avfoundation==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-avkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-businesschat==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-callkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-cfnetwork==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-classkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-cloudkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-cocoa==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-colorsync==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-contacts==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-contactsui==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-coreaudio==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-coreaudiokit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-corebluetooth==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-coredata==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-corehaptics==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-corelocation==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-coremedia==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-coremediaio==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-coremidi==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-coreml==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-coremotion==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-coreservices==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-corespotlight==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-coretext==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-corewlan==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-cryptotokenkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-devicecheck==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-discrecording==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-discrecordingui==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-diskarbitration==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-dvdplayback==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-eventkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-exceptionhandling==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-executionpolicy==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-externalaccessory==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-fileprovider==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-fileproviderui==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-findersync==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-fsevents==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-gamecenter==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-gamecontroller==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-gamekit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-gameplaykit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-imagecapturecore==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-imserviceplugin==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-installerplugins==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-intents==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-iosurface==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-ituneslibrary==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-kernelmanagement==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-latentsemanticmapping==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-launchservices==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-libdispatch==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-linkpresentation==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-localauthentication==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-mapkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-mediaaccessibility==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-medialibrary==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-mediaplayer==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-mediatoolbox==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-metal==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-metalkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-metalperformanceshaders==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-metalperformanceshadersgraph==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-mlcompute==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-modelio==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-multipeerconnectivity==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-naturallanguage==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-netfs==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-network==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-networkextension==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-notificationcenter==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-opendirectory==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-osakit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-oslog==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-passkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-pencilkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-photos==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-photosui==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-preferencepanes==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-pushkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-quartz==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-quicklookthumbnailing==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-replaykit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-safariservices==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-scenekit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-screensaver==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-screentime==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-searchkit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-security==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-securityfoundation==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-securityinterface==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-servicemanagement==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-social==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-soundanalysis==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-speech==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-spritekit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-storekit==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-syncservices==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-systemconfiguration==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-systemextensions==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-uniformtypeidentifiers==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-usernotifications==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-usernotificationsui==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-videosubscriberaccount==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-videotoolbox==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-virtualization==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-vision==7.3; platform_system == \"Darwin\"",
    "pyobjc-framework-webkit==7.3; platform_system == \"Darwin\"",
    "zeroconf==0.147.0; platform_system == \"Darwin\""
]

[project.optional-dependencies]  # This is optional dependencies
tests = [
    "pytest>=6.2.5",
    "pytest-codecov",
    "pytest-cov",
    "pytest-asyncio",
    "flake8",
    "xmlschema",
]
docs = [
    "sphinx",
    "sphinx-design",
    "sphinx-copybutton",
    "jinja2",
    "psychopy-sphinx-theme"
]
building = [
    "bdist-mpkg>=0.5.0; platform_system == \"Darwin\"",
    "py2app; platform_system == \"Darwin\"",
    "dmgbuild; platform_system == \"Darwin\"",
]
suggested = [
    "sounddevice",
    "pylsl>=1.16.1", # lab streaming layer for general connectivity
    "xlwt",  # writing excel files with pandas
    "h5py",  # to read hdf5 files for analysis
    "tobii_research",
    "badapted>=0.0.3",
    "egi-pynetstation>=1.0.0",
    "pyxid2>=1.0.5",
    "Phidget22",
]
legacy = [
    "pyo>=1.0.3",
    "pyglfw",
    "pygame",
]

[project.urls]
Homepage = "https://www.psychopy.org/"
Download = "https://github.com/psychopy/psychopy/releases/"

[build-system]
requires = [
    "pdm-backend",
    "distro; platform_system == \"Linux\"",
    "tomlkit",
    "packaging",
    "six",  # for configobj
    "polib", # for compiling translation files (*.po)
    ]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = []
excludes = ["building/"]
#source-includes = ["tests/"]

[tool.pdm.version]
source = "call"
getter = "psychopy.__init__:getVersion"

[tool.distutils.bdist_wheel]
universal = 1

[tool.psychopy]
src = ["psychopy"]
