[bdist_wheel]
universal = 1

[metadata]
license_file = LICENSE
license = GNU GPLv3 (or more recent equivalent)
author = Open Science Tools Ltd
author_email = support@opensciencetools.org
maintainer_email = support@opensciencetools.org
url = https://www.psychopy.org/
download_url = https://github.com/psychopy/psychopy/releases/
description = Psychology experiment software in Python
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Development Status :: 4 - Beta
    Operating System :: MacOS :: MacOS X
    Operating System :: Microsoft :: Windows
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8

[options]
python_requires = >=3.6
setup_requires =
    distro; platform_system == "Linux"
install_requires =
    appdirs==1.4.4; platform_system == "Windows"
    arabic-reshaper==2.1.3
    astunparse==1.6.3
    blosc2==2.0.0
    cachetools==4.2.4
    certifi==2021.10.8
    cffi==1.15.0
    charset-normalizer==2.0.7
    colorama==0.4.4; platform_system == "Windows"
    contourpy==1.0.6
    cryptography==35.0.0
    cycler==0.11.0
    cython==0.29.32
    decorator==4.4.2
    egi-pynetstation==0.0.0rc1; platform_system == "Windows"
    et-xmlfile==1.1.0
    ffpyplayer==4.3.5
    fonttools==4.38.0
    freetype-py==2.2.0
    future==0.18.2
    gevent==21.8.0
    glfw==2.4.0
    google-api-core==2.2.2
    google-auth==2.3.3
    google-cloud==0.34.0
    google-cloud-speech==2.11.1
    googleapis-common-protos==1.53.0
    greenlet==1.1.2
    grpcio==1.41.1
    grpcio-status==1.41.1
    idna==3.3
    imageio==2.10.3
    imageio-ffmpeg==0.4.5
    jedi==0.18.0
    json-tricks==3.15.5
    kiwisolver==1.3.2
    markdown-it-py==2.1.0
    matplotlib==3.4.3
    mdurl==0.1.2
    moviepy==1.0.3
    msgpack==1.0.2
    msgpack-numpy==0.4.7.1
    ntplib==0.4.0; platform_system == "Windows"
    numexpr==2.7.3
    numpy==1.21.4
    opencv-python==4.5.4.58
    openpyxl==3.0.9
    packaging==21.2
    pandas==1.3.4
    parso==0.8.2
    pillow==9.3.0
    proglog==0.1.9
    proto-plus==1.19.8
    protobuf==3.19.1
    psutil==5.8.0
    psychtoolbox==3.0.18.2
    py-cpuinfo==9.0.0
    pyasn1==0.4.8
    pyasn1-modules==0.2.8
    pycparser==2.21
    pygame==2.1.0
    pyglet==1.5.21
    pyo==1.0.4
    pyparsing==2.4.7
    pypiwin32==223; platform_system == "Windows"
    pyqmix==2021.1.2; platform_system == "Windows"
    pyqt5==5.15.7
    pyqt5-qt5==5.15.2
    pyqt5-sip==12.11.0
    pyserial==3.5
    python-bidi==0.4.2
    python-dateutil==2.8.2
    pytz==2021.3
    pywin32==302; platform_system == "Windows"
    pywinhook==1.6.2; platform_system == "Windows"
    pyyaml==6.0
    pyzmq==22.3.0
    questplus==2019.4
    requests==2.26.0
    rsa==4.7.2
    ruamel-yaml==0.16.3; platform_system == "Windows"
    scipy==1.7.2
    setuptools==65.6.3
    six==1.16.0
    sounddevice==0.4.3
    soundfile==0.11.0
    speechrecognition==3.9.0
    tables==3.6.1
    tobii-research==1.10.1
    tqdm==4.62.3
    ujson==4.2.0
    urllib3==1.26.7
    websocket-client==1.2.1
    wheel==0.38.4
    xarray==0.20.1
    xlrd==2.0.1
    zope-event==4.6
    zope-interface==5.5.2
    pyobjc==7.3; platform_system == "Darwin"
    pyobjc-core==7.3; platform_system == "Darwin"
    pyobjc-framework-accessibility==7.3; platform_system == "Darwin"
    pyobjc-framework-accounts==7.3; platform_system == "Darwin"
    pyobjc-framework-addressbook==7.3; platform_system == "Darwin"
    pyobjc-framework-adservices==7.3; platform_system == "Darwin"
    pyobjc-framework-adsupport==7.3; platform_system == "Darwin"
    pyobjc-framework-applescriptkit==7.3; platform_system == "Darwin"
    pyobjc-framework-applescriptobjc==7.3; platform_system == "Darwin"
    pyobjc-framework-applicationservices==7.3; platform_system == "Darwin"
    pyobjc-framework-apptrackingtransparency==7.3; platform_system == "Darwin"
    pyobjc-framework-authenticationservices==7.3; platform_system == "Darwin"
    pyobjc-framework-automaticassessmentconfiguration==7.3; platform_system == "Darwin"
    pyobjc-framework-automator==7.3; platform_system == "Darwin"
    pyobjc-framework-avfoundation==7.3; platform_system == "Darwin"
    pyobjc-framework-avkit==7.3; platform_system == "Darwin"
    pyobjc-framework-businesschat==7.3; platform_system == "Darwin"
    pyobjc-framework-callkit==7.3; platform_system == "Darwin"
    pyobjc-framework-cfnetwork==7.3; platform_system == "Darwin"
    pyobjc-framework-classkit==7.3; platform_system == "Darwin"
    pyobjc-framework-cloudkit==7.3; platform_system == "Darwin"
    pyobjc-framework-cocoa==7.3; platform_system == "Darwin"
    pyobjc-framework-colorsync==7.3; platform_system == "Darwin"
    pyobjc-framework-contacts==7.3; platform_system == "Darwin"
    pyobjc-framework-contactsui==7.3; platform_system == "Darwin"
    pyobjc-framework-coreaudio==7.3; platform_system == "Darwin"
    pyobjc-framework-coreaudiokit==7.3; platform_system == "Darwin"
    pyobjc-framework-corebluetooth==7.3; platform_system == "Darwin"
    pyobjc-framework-coredata==7.3; platform_system == "Darwin"
    pyobjc-framework-corehaptics==7.3; platform_system == "Darwin"
    pyobjc-framework-corelocation==7.3; platform_system == "Darwin"
    pyobjc-framework-coremedia==7.3; platform_system == "Darwin"
    pyobjc-framework-coremediaio==7.3; platform_system == "Darwin"
    pyobjc-framework-coremidi==7.3; platform_system == "Darwin"
    pyobjc-framework-coreml==7.3; platform_system == "Darwin"
    pyobjc-framework-coremotion==7.3; platform_system == "Darwin"
    pyobjc-framework-coreservices==7.3; platform_system == "Darwin"
    pyobjc-framework-corespotlight==7.3; platform_system == "Darwin"
    pyobjc-framework-coretext==7.3; platform_system == "Darwin"
    pyobjc-framework-corewlan==7.3; platform_system == "Darwin"
    pyobjc-framework-cryptotokenkit==7.3; platform_system == "Darwin"
    pyobjc-framework-devicecheck==7.3; platform_system == "Darwin"
    pyobjc-framework-discrecording==7.3; platform_system == "Darwin"
    pyobjc-framework-discrecordingui==7.3; platform_system == "Darwin"
    pyobjc-framework-diskarbitration==7.3; platform_system == "Darwin"
    pyobjc-framework-dvdplayback==7.3; platform_system == "Darwin"
    pyobjc-framework-eventkit==7.3; platform_system == "Darwin"
    pyobjc-framework-exceptionhandling==7.3; platform_system == "Darwin"
    pyobjc-framework-executionpolicy==7.3; platform_system == "Darwin"
    pyobjc-framework-externalaccessory==7.3; platform_system == "Darwin"
    pyobjc-framework-fileprovider==7.3; platform_system == "Darwin"
    pyobjc-framework-fileproviderui==7.3; platform_system == "Darwin"
    pyobjc-framework-findersync==7.3; platform_system == "Darwin"
    pyobjc-framework-fsevents==7.3; platform_system == "Darwin"
    pyobjc-framework-gamecenter==7.3; platform_system == "Darwin"
    pyobjc-framework-gamecontroller==7.3; platform_system == "Darwin"
    pyobjc-framework-gamekit==7.3; platform_system == "Darwin"
    pyobjc-framework-gameplaykit==7.3; platform_system == "Darwin"
    pyobjc-framework-imagecapturecore==7.3; platform_system == "Darwin"
    pyobjc-framework-imserviceplugin==7.3; platform_system == "Darwin"
    pyobjc-framework-installerplugins==7.3; platform_system == "Darwin"
    pyobjc-framework-intents==7.3; platform_system == "Darwin"
    pyobjc-framework-iosurface==7.3; platform_system == "Darwin"
    pyobjc-framework-ituneslibrary==7.3; platform_system == "Darwin"
    pyobjc-framework-kernelmanagement==7.3; platform_system == "Darwin"
    pyobjc-framework-latentsemanticmapping==7.3; platform_system == "Darwin"
    pyobjc-framework-launchservices==7.3; platform_system == "Darwin"
    pyobjc-framework-libdispatch==7.3; platform_system == "Darwin"
    pyobjc-framework-linkpresentation==7.3; platform_system == "Darwin"
    pyobjc-framework-localauthentication==7.3; platform_system == "Darwin"
    pyobjc-framework-mapkit==7.3; platform_system == "Darwin"
    pyobjc-framework-mediaaccessibility==7.3; platform_system == "Darwin"
    pyobjc-framework-medialibrary==7.3; platform_system == "Darwin"
    pyobjc-framework-mediaplayer==7.3; platform_system == "Darwin"
    pyobjc-framework-mediatoolbox==7.3; platform_system == "Darwin"
    pyobjc-framework-metal==7.3; platform_system == "Darwin"
    pyobjc-framework-metalkit==7.3; platform_system == "Darwin"
    pyobjc-framework-metalperformanceshaders==7.3; platform_system == "Darwin"
    pyobjc-framework-metalperformanceshadersgraph==7.3; platform_system == "Darwin"
    pyobjc-framework-mlcompute==7.3; platform_system == "Darwin"
    pyobjc-framework-modelio==7.3; platform_system == "Darwin"
    pyobjc-framework-multipeerconnectivity==7.3; platform_system == "Darwin"
    pyobjc-framework-naturallanguage==7.3; platform_system == "Darwin"
    pyobjc-framework-netfs==7.3; platform_system == "Darwin"
    pyobjc-framework-network==7.3; platform_system == "Darwin"
    pyobjc-framework-networkextension==7.3; platform_system == "Darwin"
    pyobjc-framework-notificationcenter==7.3; platform_system == "Darwin"
    pyobjc-framework-opendirectory==7.3; platform_system == "Darwin"
    pyobjc-framework-osakit==7.3; platform_system == "Darwin"
    pyobjc-framework-oslog==7.3; platform_system == "Darwin"
    pyobjc-framework-passkit==7.3; platform_system == "Darwin"
    pyobjc-framework-pencilkit==7.3; platform_system == "Darwin"
    pyobjc-framework-photos==7.3; platform_system == "Darwin"
    pyobjc-framework-photosui==7.3; platform_system == "Darwin"
    pyobjc-framework-preferencepanes==7.3; platform_system == "Darwin"
    pyobjc-framework-pushkit==7.3; platform_system == "Darwin"
    pyobjc-framework-quartz==7.3; platform_system == "Darwin"
    pyobjc-framework-quicklookthumbnailing==7.3; platform_system == "Darwin"
    pyobjc-framework-replaykit==7.3; platform_system == "Darwin"
    pyobjc-framework-safariservices==7.3; platform_system == "Darwin"
    pyobjc-framework-scenekit==7.3; platform_system == "Darwin"
    pyobjc-framework-screensaver==7.3; platform_system == "Darwin"
    pyobjc-framework-screentime==7.3; platform_system == "Darwin"
    pyobjc-framework-searchkit==7.3; platform_system == "Darwin"
    pyobjc-framework-security==7.3; platform_system == "Darwin"
    pyobjc-framework-securityfoundation==7.3; platform_system == "Darwin"
    pyobjc-framework-securityinterface==7.3; platform_system == "Darwin"
    pyobjc-framework-servicemanagement==7.3; platform_system == "Darwin"
    pyobjc-framework-social==7.3; platform_system == "Darwin"
    pyobjc-framework-soundanalysis==7.3; platform_system == "Darwin"
    pyobjc-framework-speech==7.3; platform_system == "Darwin"
    pyobjc-framework-spritekit==7.3; platform_system == "Darwin"
    pyobjc-framework-storekit==7.3; platform_system == "Darwin"
    pyobjc-framework-syncservices==7.3; platform_system == "Darwin"
    pyobjc-framework-systemconfiguration==7.3; platform_system == "Darwin"
    pyobjc-framework-systemextensions==7.3; platform_system == "Darwin"
    pyobjc-framework-uniformtypeidentifiers==7.3; platform_system == "Darwin"
    pyobjc-framework-usernotifications==7.3; platform_system == "Darwin"
    pyobjc-framework-usernotificationsui==7.3; platform_system == "Darwin"
    pyobjc-framework-videosubscriberaccount==7.3; platform_system == "Darwin"
    pyobjc-framework-videotoolbox==7.3; platform_system == "Darwin"
    pyobjc-framework-virtualization==7.3; platform_system == "Darwin"
    pyobjc-framework-vision==7.3; platform_system == "Darwin"
    pyobjc-framework-webkit==7.3; platform_system == "Darwin"

[versioneer]
VCS = git
style = pep440
versionfile_source = psychopy/_version.py
versionfile_build =
tag_prefix = ''

[codespell]
skip = ./.git,static,_static
ignore-words-list = ans,extraversion,numer,ontext,ser,signall,statics,sur,tesselate,tesselated,tesselation,wit
